{{- if .Values.useTraefikLe}}
apiVersion: {{ .Values.traefik_crd_api_version }}
kind: IngressRoute
metadata:
  name: web-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.leHost}}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-ui-service
      port: {{ .Values.uiService.port }}
{{- if eq .Values.projectProtocol "https" }}
    middlewares:
      - name: redirect
{{- end }}
---
apiVersion: {{ .Values.traefik_crd_api_version }}
kind: IngressRoute
metadata:
  name: websecure-ingressroute
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.leHost}}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-ui-service
      port: {{ .Values.uiService.port }}
  tls:
    certResolver: le
---
apiVersion: {{ .Values.traefik_crd_api_version }}
kind: Middleware
metadata:
  name: redirect
  namespace: {{ .Values.namespace }}
spec:
  redirectScheme:
    scheme: https
{{- end}}
{{- if .Values.traefikBehindLb}}
apiVersion: {{ .Values.traefik_crd_api_version }}
kind: IngressRoute
metadata:
  name: web-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.leHost}}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-ui-service
      port: {{ .Values.uiService.port }}
{{- end}}