apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui-service
  namespace: {{ .Release.Namespace }}
  labels:
    name: rearm-ui-service
    {{- include "rearm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.uiService.type }}
  ports:
    - port: {{ .Values.uiService.port }}
      targetPort: {{ .Values.uiService.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.uiService.type "NodePort" }}
      nodePort: {{ .Values.uiService.nodePort }}
      {{- end }}
  selector:
    {{- include "rearm.selectorLabels" . | nindent 4 }}
    servicehook: {{ .Release.Name }}-ui

---
{{- if .Values.isLocalDeployment }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectHost }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rearm.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: rearm-ui-service.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}