backendReplicaCount: 1
uiReplicaCount: 1
ociArtifactReplicaCount: 1
enableBetaTea: false

use_external_postgres: false
rearm_postgres_host: ""
rearm_postgres_database: "postgres"
rearm_postgres_username: "postgres"
rearm_postgres_port: "5432"

keycloak_postgres_host: ""
keycloak_postgres_username: "postgres"
keycloak_postgres_database: "postgres"
keycloak_postgres_port: "5432"

rebom_postgres_host: ""
rebom_postgres_database: "postgres"
rebom_postgres_username: "postgres"
rebom_postgres_ssl: "false"
rebom_postgres_port: "5432"

traefik_crd_api_version: traefik.containo.us/v1alpha1

image:
  backEndImage: registry.relizahub.com/library/rearm-backend:26.04.38@sha256:f6ce129d92529c6cefd421e20c788c9ce2c7211d1e0477a9987ead37c3197f36
  uiImage: registry.relizahub.com/library/rearm-ui:26.04.28@sha256:4d9ba551c90828de3a49c0acdf50699f0900b62617e5311a06728ff7ec6c8c9e
  ociArtifactImage: registry.relizahub.com/library/rearm-oci-artifact-service:26.03.11@sha256:8f815f7195a89cbaaa8d040b6c3df2bb0a7d5229a8bf5503f9f12a3f0acd1ff7
  keycloakImage: registry.relizahub.com/library/rearm-keycloak:26.03.3@sha256:7ad8cbd62d4ddfabfa47fc040d65c73188387a66af8c499dc01cb2718a1bc929
  postgresImage: registry.relizahub.com/library/rearm-postgres:0.1.6@sha256:7c3d99ee4d4bbfb9a784f4e35e653aea07ebdf4ce32cd90f85fd888e717612ee
  rebomBackend: registry.relizahub.com/library/rebom-backend:0.17.7@sha256:5f9c5e46d6a87da3d0257d272476c5da32092e7dbbb1f4a742f6603b75cb5f58
  flywayImage: docker.io/redgate/flyway:11.20.3-alpine@sha256:52cdd559dc8ae38a17b56615e3c7137d9b01470271112525b40373de470bb005
  pullPolicy: IfNotPresent

imagePullSecrets: [ {"name":"regcred"} ]
nameOverride: "rearm"
fullnameOverride: ""

projectProtocol: http
projectHost: rearm.localhost
useDefaultSecrets: true
max_upload_size_in_MB: 50
backend:
  logFormatType: "plain"
  enableDtrackCleanupScheduler: false

keycloak:
  enabled: true
  postgresStorage: 4G
  create_secret_in_chart: regular # regular, none, sealed; sealed supported by Reliza Hub
  sealed_secrets_scope: namespace-wide # namespace-wide, cluster-wide, strict
  strict_host: false
  issuer_uri: http://rearm.localhost
  set_uri: http://keycloak:9080
  secrets:
    pgpassword: VKKlL0ZxfCjPWElRMjFpHg # change for prod use
    adminpassword: admin # change for prod use

backendService:
  type: ClusterIP
  port: 8085
  resources:
    requests:
      memory: "300Mi"
      cpu: "10m"
    limits:
      memory: "4000Mi"
      cpu: "4000m"

uiService:
  type: ClusterIP
  port: 80
  targetPort: 80
  nodePort: 30001
  resources:
    requests:
      memory: "100Mi"
      cpu: "10m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"

ociArtifactService:
  enabled: true
  logFormatType: "plain"
  logLevel: "info"
  usePlainHttp: false
  registryHost: registry.relizahub.com
  registryUser: changeme # change
  registryToken: changeme # change
  create_secret_in_chart: true

useTraefikLe: true
traefikBehindLb: false
leHost: rearm.localhost

postgresql:
  image:
    registry: registry.relizahub.com
    repository: library/rearm-postgres
    tag: "0.1.0"
    digest: "sha256:b15503aa3dbd5c3c1c9519ba1f2ce5c1c0e322132fb6f666ecc5780157f123c3"
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## Example:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
    ## Set to true if you would like to see extra information on logs
    ##
    debug: false
  auth:
    enablePostgresUser: true
    postgresPassword: relizaPass # change for prod use
  persistence:
    size: 4Gi
  primary:
    resources:
      requests:
        memory: "300Mi"
        cpu: "10m"
      limits:
        memory: "4000Mi"
        cpu: "4000m"

rebom:
  postgresStorage: 5Gi
  backend:
    replicaCount: 1
    logFormatType: "plain"
    oci:
      enabled: "true"
      serviceHost: http://rearm-oci-artifact
      registryNamespace: 123-placeholder
    enrichmentPendingIfNotConfigured: false
    rebomPropsSecretName: ""