backendReplicaCount: 1
uiReplicaCount: 1
ociArtifactReplicaCount: 1
enableBetaTea: false

use_external_postgres: false
rearm_postgres_host: ""
rearm_postgres_database: "postgres"
rearm_postgres_username: "postgres"
rearm_postgres_port: "5432"

keycloak_postgres_host: ""
keycloak_postgres_username: "postgres"
keycloak_postgres_database: "postgres"
keycloak_postgres_port: "5432"

rebom_postgres_host: ""
rebom_postgres_database: "postgres"
rebom_postgres_username: "postgres"
rebom_postgres_ssl: "false"
rebom_postgres_port: "5432"

traefik_crd_api_version: traefik.containo.us/v1alpha1

image:
  backEndImage: registry.relizahub.com/library/rearm-backend:26.03.16@sha256:6349bc222fccbeb3142d4873b04fbc5638e82b3f4710ceb0ab75bfb095f335ab
  uiImage: registry.relizahub.com/library/rearm-ui:26.03.20@sha256:01ab350a04ab677d6c07bac2fdf4b83f80354e16be0567dd437869f3309b5eed
  ociArtifactImage: registry.relizahub.com/library/rearm-oci-artifact-service:26.03.0@sha256:294b9cd5f55c0d59531c503ae03fd9d8fa2b123c2316a21e051dfe1594129d82
  keycloakImage: registry.relizahub.com/library/rearm-keycloak:26.03.0@sha256:7e4d664ed621420acf7995b9369620c9cba5f68a4725116a96aba1f37588245e
  postgresImage: registry.relizahub.com/library/rearm-postgres:0.1.3@sha256:3c52805d1d6d09147fd469dba80b7962ba051ba3f6ac15ed4962945b274bcd56
  rebomBackend: registry.relizahub.com/library/rebom-backend:0.15.12@sha256:e0d7f332dfe915c35fb9552ea7491d374459693a9a4b28c80df2e4d1cd33db58
  flywayImage: docker.io/redgate/flyway:11.20.3-alpine@sha256:52cdd559dc8ae38a17b56615e3c7137d9b01470271112525b40373de470bb005
  pullPolicy: IfNotPresent

imagePullSecrets: [ {"name":"regcred"} ]
nameOverride: "rearm"
fullnameOverride: ""

projectProtocol: http
projectHost: rearm.localhost
useDefaultSecrets: true
max_upload_size_in_MB: 50
backend:
  logFormatType: "plain"
  enableDtrackCleanupScheduler: false

keycloak:
  enabled: true
  postgresStorage: 4G
  create_secret_in_chart: regular # regular, none, sealed; sealed supported by Reliza Hub
  sealed_secrets_scope: namespace-wide # namespace-wide, cluster-wide, strict
  strict_host: false
  issuer_uri: http://rearm.localhost
  set_uri: http://keycloak:9080
  secrets:
    pgpassword: VKKlL0ZxfCjPWElRMjFpHg # change for prod use
    adminpassword: admin # change for prod use

backendService:
  type: ClusterIP
  port: 8085
  resources:
    requests:
      memory: "300Mi"
      cpu: "10m"
    limits:
      memory: "4000Mi"
      cpu: "4000m"

uiService:
  type: ClusterIP
  port: 80
  targetPort: 80
  nodePort: 30001
  resources:
    requests:
      memory: "100Mi"
      cpu: "10m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"

ociArtifactService:
  enabled: true
  logFormatType: "plain"
  registryHost: registry.relizahub.com/123-private # change
  registryUser: changeme # change
  registryToken: changeme # change
  create_secret_in_chart: true

useTraefikLe: true
traefikBehindLb: false
leHost: rearm.localhost

postgresql:
  image:
    registry: registry.relizahub.com
    repository: library/rearm-postgres
    tag: "0.1.0"
    digest: "sha256:b15503aa3dbd5c3c1c9519ba1f2ce5c1c0e322132fb6f666ecc5780157f123c3"
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## Example:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
    ## Set to true if you would like to see extra information on logs
    ##
    debug: false
  auth:
    enablePostgresUser: true
    postgresPassword: relizaPass # change for prod use
  persistence:
    size: 4Gi
  primary:
    resources:
      requests:
        memory: "300Mi"
        cpu: "10m"
      limits:
        memory: "4000Mi"
        cpu: "4000m"

rebom:
  postgresStorage: 5Gi
  backend:
    replicaCount: 1
    logFormatType: "plain"
    oci:
      enabled: "true"
      serviceHost: http://rearm-oci-artifact
      registryNamespace: 123-placeholder
    enrichmentPendingIfNotConfigured: false
    rebomPropsSecretName: ""