// Code generated by github.com/edwarnicke/imports-gen DO NOT EDIT.
package imports

import (
	_ "context"
	_ "crypto/sha256"
	_ "fmt"
	_ "github.com/gabriel-vasile/mimetype"
	_ "github.com/gin-gonic/gin"
	_ "github.com/opencontainers/image-spec/specs-go/v1"
	_ "io"
	_ "log"
	_ "mime/multipart"
	_ "net/http"
	_ "oras.land/oras-go/v2"
	_ "oras.land/oras-go/v2/content/file"
	_ "oras.land/oras-go/v2/registry/remote"
	_ "oras.land/oras-go/v2/registry/remote/auth"
	_ "oras.land/oras-go/v2/registry/remote/retry"
	_ "os"
	_ "path/filepath"
	_ "strings"
)
