parameters:
  - name: name
    type: string
  - name: imageRepository
    type: string
  - name: containerRegistry
    type: string
  - name: dockerfilePath
    type: string
  - name: tag
    type: string
  - name: branch
    type: string
  - name: commit
    type: string
  - name: buildUri
    type: string
  - name: vmImageName
    type: string
  - name: dockerRegistryServiceConnection
    type: string
  - name: rearmUrl
    type: string
  - name: rearmApiKey
    type: string
  - name: rearmApiKeyId
    type: string
  - name: buildPath
    type: string
  - name: pushLatestTag
    type: string
  - name: enableSbom
    type: string
  - name: sbomType
    type: string
  - name: dotnetSlnFilePath
    type: string
    default: placeholder


jobs:
- job: Build_${{ parameters.name }}
  displayName: Build ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImageName }}
  steps:
  - task: RearmCliInstall@1.1.7
    name: RearmCliInstall
  - checkout: self
    fetchDepth: "0"
  - bash: |
      ls
  - task: gitversion/setup@4.1.0
    displayName: Install GitVersion
    inputs:
      versionSpec: '6.4.0'
  - task: gitversion/execute@4.1.0
    displayName: Determine Version
    inputs:
      useConfigFile: true
      configFilePath: ./GitVersion.yml
  - bash: |
      echo "Full GitVersion Semver: $(GitVersion_FullSemVer)"
      echo "Short Semver: $(GitVersion_SemVer)"
      mkdir -p $(Pipeline.Workspace)/variables
      echo -n "$(GitVersion_FullSemVer)" > $(Pipeline.Workspace)/variables/RLZ_FULL_VER
      echo -n "$(GitVersion_SemVer)" > $(Pipeline.Workspace)/variables/RLZ_SHORT_VER
    displayName: Store version data for future use
  - task: RearmReleaseInitialize@1.1.7
    inputs:
      rearmApiKey: ${{ parameters.rearmApiKey }}
      rearmApiKeyId: ${{ parameters.rearmApiKeyId }}
      rearmUrl: ${{ parameters.rearmUrl }}
      repoPath: ${{ parameters.buildPath }}
      allowRebuild: true
  - task: Docker@2
    displayName: Login to Container Registry
    inputs:
      command: login
      containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
  - task: UseNode@1
    inputs:
      version: '22.19.0'
    displayName: 'Install Node.js'
  - bash: npm install --global @cyclonedx/cyclonedx-npm@4.0.0 --ignore-scripts
    condition: ${{ eq(parameters.sbomType, 'npm') }}
    displayName: 'Install cyclonedx npm'
  - task: UseDotNet@2
    condition: ${{ eq(parameters.sbomType, 'dotnet') }}
    inputs:
      version: '9.0.100'
    displayName: 'Install .NET SDK'
  - bash: dotnet tool install --global CycloneDX
    condition: ${{ eq(parameters.sbomType, 'dotnet') }}
    displayName: 'Install cyclonedx .NET'
  - bash: npm install -g @cyclonedx/cdxgen@11.9.0 --ignore-scripts
    displayName: 'Install cdxgen cli'
  - bash: |
      echo "##vso[task.setvariable variable=REARM_LIFECYCLE]REJECTED"
      echo "##vso[task.setvariable variable=REARM_PURL]"
      echo "##vso[task.setvariable variable=REARM_DIGESTS]"
      echo "##vso[task.setvariable variable=REARM_CLEANED_BRANCH]"
      echo "##vso[task.setvariable variable=REARM_ODEL_ID]"
      echo "##vso[task.setvariable variable=REARM_ODEL_ARTS_JSON]"
      echo "##vso[task.setvariable variable=REARM_SCE_ARTS]"
    displayName: Initialize variables with defaults for possible build failure
  - bash: |
      set +e
      set -x
      dirtybranch=${{ parameters.branch }}
      cleanedbranch="${dirtybranch/'refs/heads/'/''}"
      cleanedbranch="${cleanedbranch/'/'/'-'}"
      cd ${{ parameters.buildPath }}
      case $cleanedbranch in

        master | main)
          latest_tag=latest
          ;;

        *)
          latest_tag=$cleanedbranch
          ;;
      esac

      tags="-t ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:$(cat $(Pipeline.Workspace)/variables/RLZ_SHORT_VER)"
      if [ "${{ parameters.pushLatestTag }}" = "true" ] || [ "$latest_tag" != "latest" ]; then
        tags+=" -t ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:$latest_tag"
      fi

      echo "tags=" $tags
      # push branch tag for main or master
      if [ "$latest_tag" != "$cleanedbranch" ]
      then
        tags+=" -t ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:$cleanedbranch"
      fi

      echo "starting build..."
      docker_sha_256=""
      docker buildx build --push \
        $tags \
        --build-arg CI_ENV=azuredevops${{ parameters.tag }} --build-arg GIT_COMMIT=${{ parameters.commit }} --build-arg GIT_BRANCH=${{ parameters.branch }} \
        --build-arg VERSION=$(cat $(Pipeline.Workspace)/variables/RLZ_FULL_VER) -f ${{ parameters.dockerfilePath }} \
        .
      exit_code=$?

      if [[ $exit_code -eq 0 ]]
      then
        docker_sha_256=$(docker buildx imagetools inspect --format "{{json .Manifest}}" ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:$(cat $(Pipeline.Workspace)/variables/RLZ_SHORT_VER) | jq -r '.digest')
        # set reliza release lifecycle to ASSEMBLED
        echo "##vso[task.setvariable variable=REARM_LIFECYCLE]ASSEMBLED"
        # establish purl
        url4purl=oci://${{parameters.containerRegistry }}:${{parameters.imageRepository}}
        docker pull registry.relizahub.com/library/url2purl-cli:25.07.0@sha256:05f849cfedbc31c6c8d11819e42efb4eb5e95198696978ca1ad84b010d52e952
        purl=$(docker run --rm registry.relizahub.com/library/url2purl-cli:25.07.0@sha256:05f849cfedbc31c6c8d11819e42efb4eb5e95198696978ca1ad84b010d52e952 $url4purl)
        echo "deliverable purl=$purl"
        echo "##vso[task.setvariable variable=REARM_PURL]$purl"
        echo "##vso[task.setvariable variable=REARM_DIGESTS]$docker_sha_256"
        echo "##vso[task.setvariable variable=REARM_CLEANED_BRANCH]$cleanedbranch"
        echo "##vso[task.setvariable variable=REARM_ODEL_ID]${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:$cleanedbranch"

        # generate sboms
        if [ "${{ parameters.enableSbom }}" = "true" ]; then
          if [ "${{ parameters.sbomType }}" = "dotnet" ]; then
              dotnet-CycloneDX ${{ parameters.dotnetSlnFilePath }} -o ./ -fn fs.cdx.bom.json -j
          elif [ "${{ parameters.sbomType }}" = "npm" ]; then
              npm ci
              cyclonedx-npm > fs.cdx.bom.json
          else
              cdxgen ./ --project-version "$(GitVersion_FullSemVer)" -o fs.cdx.bom.json
          fi
          cp fs.cdx.bom.json $(Pipeline.Workspace)/variables/fs.cdx.bom.json

          cdxgen -t docker --lifecycle build -o docker.cdx.bom.tmp.json --project-version $(cat $(Pipeline.Workspace)/variables/RLZ_FULL_VER) ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:$(cat $(Pipeline.Workspace)/variables/RLZ_SHORT_VER)
          
          cat docker.cdx.bom.tmp.json | $(RearmCliInstall.RearmCli) bomutils fixpurl --newpurl "${purl}" > $(Pipeline.Workspace)/variables/docker.cdx.bom.json
          workspace_path="$(Pipeline.Workspace)"
          echo "##vso[task.setvariable variable=REARM_ODEL_ARTS_JSON][{\"bomFormat\": \"CYCLONEDX\",\"type\": \"BOM\",\"filePath\": \"${workspace_path}/variables/docker.cdx.bom.json\"}]"
          echo "##vso[task.setvariable variable=REARM_SCE_ARTS][{\"bomFormat\": \"CYCLONEDX\",\"type\": \"BOM\",\"filePath\": \"${workspace_path}/variables/fs.cdx.bom.json\"}]"
        fi
      fi
    displayName: 'Build Container and Generate SBOMs'
  - task: RearmReleaseFinalize@1.1.7
    inputs:
      rearmApiKey: ${{ parameters.rearmApiKey }}
      rearmApiKeyId: ${{ parameters.rearmApiKeyId }}
      rearmUrl: ${{ parameters.rearmUrl }}
      repoPath: ${{ parameters.buildPath }}
      lifecycle: $(REARM_LIFECYCLE)
      odelId: $(REARM_ODEL_ID)
      odelType: CONTAINER
      odelBuildId: azuredevops${{ parameters.tag }}
      odelBuildUri: ${{ parameters.buildUri }}
      odelPurl: $(REARM_PURL)
      odelDigests: $(REARM_DIGESTS)
      odelArtsJson: $(REARM_ODEL_ARTS_JSON)
      sceArts: $(REARM_SCE_ARTS)
