FROM ghcr.io/cyclonedx/cdxgen:v12.3.3@sha256:9696cf075974cca979da8c11d20211e0097585382be4ea617a2a23b364798eaa AS sbom-stage
ARG VERSION
USER root
RUN mkdir /sbom && chown cyclonedx:cyclonedx /sbom
USER cyclonedx
WORKDIR /app
COPY . .
RUN export FETCH_LICENSE=true && cdxgen ./ -t go --project-version $VERSION --spec-version 1.6 -o /sbom/sbom.json