FROM golang:1.26.3-trixie@sha256:d08bf3ed2bd263088ca8e23fefaf10f1b71769f6932f0a4017ba28d2a5baf001 AS build-stage
ARG CODEQL_BUNDLE_VERSION=2.25.4
ARG CODEQL_URL="https://github.com/github/codeql-action/releases/download/codeql-bundle-v${CODEQL_BUNDLE_VERSION}/codeql-bundle-linux64.tar.gz"

RUN curl -sSL "$CODEQL_URL" -o /tmp/codeql.tgz \
    && echo "5a68ac6f65cc4c10e04974ae7bd022fca68128f1eaa4d2c59e4f7d8f5893d881  /tmp/codeql.tgz" | sha256sum -c - \
    && mkdir -p /opt/codeql \
    && tar -xzf /tmp/codeql.tgz -C /opt/codeql --strip-components=1 \
    && rm /tmp/codeql.tgz

ENV PATH="/opt/codeql:${PATH}"

RUN mkdir /sarif

WORKDIR /build
ENV CGO_ENABLED=0
COPY go.mod go.sum ./
COPY ./internal/imports ./internal/imports
RUN go build ./internal/imports
COPY . .
RUN codeql database create qldb --language=go
RUN codeql database analyze qldb --format=sarifv2.1.0 --output=/sarif/results.sarif