/**
* Copyright Reliza Incorporated. 2019 - 2026. All rights reserved.
*/
package io.reliza.model.dto.notifications;

/**
 * Subscription CEL filters compile in one of two modes. Extracted to a
 * shared top-level enum (was nested in the Pro-only CEL evaluator) so
 * the shared notification subscription model/DTOs and the
 * {@code NotificationCelEvaluator} seam can reference it without
 * pulling in the {@code saas/} evaluator implementation.
 */
public enum EvaluationMode {
    /** Toggle-driven expression generated by the server from the customer's preset config. */
    PRESET,
    /** User-typed CEL behind the per-org "Advanced filtering" feature flag. */
    ADVANCED;
}
