FROM node:24.13.0-alpine3.23@sha256:cd6fb7efa6490f039f3471a189214d5f548c11df1ff9e5b181aa49e22c14383e AS build-stage
RUN mkdir /sbom && npm install -g @cyclonedx/cyclonedx-npm@4.1.2
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
RUN cyclonedx-npm > /sbom/sbom.json