FROM node:24.18.0-alpine3.24@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd AS build-stage
RUN mkdir /sbom && npm install -g @cyclonedx/cyclonedx-npm@5.0.0
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
RUN cyclonedx-npm > /sbom/sbom.json