FROM ghcr.io/cyclonedx/cdxgen:v12.6.0@sha256:0417ba8ca67bd49d37ba25208bb71076e0324f99f97036064216d8d1d6b6bdd0 AS sbom-stage
ARG VERSION
USER root
RUN mkdir /sbom && chown cyclonedx:cyclonedx /sbom
USER cyclonedx
WORKDIR /app
COPY . .
RUN export FETCH_LICENSE=true && cdxgen ./ -t npm --project-version $VERSION -o /sbom/sbom.json