version: '3.8'
services:
  keycloak:
    image: kc:local10
    # build: ../
    ports:
     - "9080:9080"
    environment:
     - KC_DB=postgres
     - KC_DB_SCHEMA=reliza_keycloak
     - KC_DB_USERNAME=postgres
     - KC_DB_PASSWORD=relizaPass
     - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/postgres
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin
     - KC_HTTP_RELATIVE_PATH=kauth
     - KC_HEALTH_ENABLED=true
    entrypoint:
     - /bin/sh
     - -c
     - /opt/keycloak/bin/kc.sh start --import-realm --http-enabled true --hostname-strict false --http-host 0.0.0.0 --http-port 9080 --hostname http://localhost:3000/kauth
    depends_on:
     - keycloak-postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
  keycloak-postgres:
    image: bitnami/postgresql:17.5.0-debian-12-r4
    environment:
     - POSTGRES_PASSWORD=relizaPass
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
      - "rearm-keycloak-postgres-data:/var/lib/postgresql/data"
volumes:
  rearm-keycloak-postgres-data:
    driver: local